#!/bin/bash

# case4-2: Перевірка символа
read -n 1 -p "Type a charecter > "
echo
case "$REPLY" in
	[[:upper:]]) echo "'$REPLY' is upper case." ;;&
	[[:lower:]]) echo "'$REPLY' is lower case." ;;&
	[[:alpha:]]) echo "'$REPLY' is alphabetic." ;;& 
	[[:digit:]]) echo "'$REPLY' is a digit." ;;&
	[[:graph:]]) echo "'$REPLY' is a visible charecter." ;;&
	[[:punct:]]) echo "'$REPLY' is a punctuation symbol." ;;&
	[[:space:]]) echo "'$REPLY' is a whitespace character." ;;&
	[[:xdigit:]]) echo "'$REPLY' is a hexadecimal digit." ;;&
esac
