#!/bin/bash

# Roman

# Додавання report_iptime 14 лютого

TITLE="System Information Report for $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"
cat <<- _EOF_
<html>
  <head>
    <title>System Information Report For linuxbox</title>
  </head>
  <body>
    <h1>System Information Report For linuxbox</h1>
    <p>Generated 02/19/2023 21:51:25 PM EDT, by Roman</p>

                   <h2>System Uptime</h2>
                   <pre>$(uptime)</pre>
   
    
                   <h2>Disk Space Utilization</h2>
		   <pre>$(df -h)</pre>

                   <h2>Home Space Utilization</h2>
		   <pre>$(du -sh /home/*)</pre>
		   
		   report_home_space () {
      if [[ $(id -u) -eq 0 ]]; then
             cat <<- _EOF_
                    <h2>Home Space Unilization (All Users)</h2>
                    <pre>$(du -sh /home/*)</pre>
                    _EOF_
	    else
             cat <<- _EOF_
             <h2>Home Space Utilization ($USER)</h2>
             <pre>$(du -sh $HOME)</pre>
             _EOF_
      fi
      return
}

usage () {
	echo "$PROGNAME: usage: $PROGNAME [-f file | -i]"
	return
}

# Обробка параметрів командної строки

interactive=
filename=
while [[ -n "$1" ]]; do
	case "$1" in
		-f | --file)
			shift
			filename="$1"
		
# інтерактивний режим

if [[ -n "$interactive" ]]; then
	while true; do
		read -p "Enter name of output file: " filename
		if [[ -e "$filename" ]]; then
			read -p "'$filename' exists. Overwrite? [y/n/q] > "
			case "$REPLY" in
				Y|y) break
					;;
				Q|q) echo "Program terminated."
					exit
					;;
				*) continue
					;;
			esac
		elif [[ -z "$filename" ]]; then
			continue
		else
			break
		fi
	done
fi

write_html_page () {
	cat <<- _EOF_
<html>
<head>
<title>$TITLE</title>
</head>
<body>
<h1>$TITLE</h1>
<p>$TIME_STAMP</p>
$(report_uptime)
$(report_disk_space)
$(report_home_space)
</body>
</html>
_EOF_
return
}

# вивід сторінки html

if [[ -n "filename" ]]; then
	if toush "$filename" && [[ -f "$filename" ]]; then
		write_html_page > "$filename"
	else
		echo "$PROGNAME: Cannot write file '$filename'" >&2
	fi

		exit 1
	fi
	write_html_page
fi
