#!/bin/bash

# local-cars: сценарій, демонструючий локальні зміни

foo=0   # глобальна змінна foo

funct_1 () {

      local foo  # змінна foo,  локальна для funch_1

      foo=1
      echo "funch_1: foo = $foo"
}

funct_2 () {

      local foo  # змінна foo,  локальна для funch_2

      foo=2
      echo "funch_2: foo = $foo"
}

echo "global: foo = $foo"
funct_1
echo "global: foo = $foo"
funct_2
echo "global: foo = $foo"
