#!/bin/bash

# longest-world : пошук самої довшого рядка в файлі.

for i; do
	if [[ -r "$i" ]]; then
		max_word=
		max_len=
		for j in $(string $i); do
			len="${#j}"
			if (( len > max_len )); then
				max_len="$len"
				max_word="$j"
	fi
done
echo "$i: '$max_word' ($max_len charecters)"
fi
done
