#!/bin/bash

# pro-sub : Демонстрація підстановки процесів.

while read attr links owner size date time filename; do
	cat <<- EOF
Filename:     $filename
Size:         $size
Owner:        $owner
Group:        $group
Modifiled:    $date $time
Links:        $links
Attributes:   $attr
EOF
done < <(ls -l | tail  -n +2)
