#!/bin/bash

usage () {
	echo "$PROGNAME: usage: $PROGNAME [-f file | -i]"
	return
}

# Обробка параметрів командної строки

interactive=
filebame=
while [[ -n "$1" ]]; do
	case "$1" in
		-f | --file)
			shift
			filename"$1"
			;;
		-h | --help)  usage
			exit
			;;
		*) usage >&2
			exit 1
			;;
	esac
	shift
done


# Інтерактивний режим

if [[ -n "$interactive" ]]; then
	while true; do
		read -p "Enter name of output file: " filename
		if [[ -e "$filename" ]]; then
			read -p "'$filename' exits. Overwrite? [y/n/q] > "
			case "$REPLY" in
				Y|y) break
					;;
				Q|q) echo "Program terminated."
					exit
					;;
				*) continue
					;;
			esac
		elif [[ -z "$filename" ]]; then
			continue
		else
			break
		fi
	done
fi
