#!/bin/bash

# while-read2: читання рядків з файла.

sort -k 1,1 -k 2n distros.txt | while read distro version release; do
printf "Distro: %s\tVersion: %s\tReleased: %s\n" \
	"$distro" \
	"$version" \
	"$release"
done
